# action.yml
name: 'nixci'
description: 'Build ci derivation with nix'
inputs:
  CI_NAME:  # id of input
    description: 'Name of the ci derivation'
    required: true
    default: 'ci'
  NIX_PATH:  # id of input
    description: 'Path to the default.nix file'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.CI_NAME }}
